"""Database abstraction layer — protocol and factory."""

from typing import Protocol


class StacksDB(Protocol):
    async def list_stacks(self, q: str | None = None, namespace: str | None = None,
                    target: str | None = None, sort: str = "updated",
                    page: int = 1, per_page: int = 20) -> tuple[list[dict], int]: ...
    async def get_stack(self, namespace: str, name: str) -> dict | None: ...
    async def get_stack_version(self, namespace: str, name: str, version: str) -> dict | None: ...
    async def get_namespace_with_stacks(self, namespace: str) -> dict | None: ...
    async def create_namespace(self, name: str, github_org: str) -> dict: ...
    async def create_stack(self, namespace: str, name: str, description: str) -> dict: ...
    async def create_version(self, namespace: str, name: str, version_data: dict) -> dict: ...
    async def version_exists(self, namespace: str, name: str, version: str) -> bool: ...
    async def featured_stacks(self, limit: int = 6) -> list[dict]: ...
    async def all_versions(self, namespace: str, name: str) -> list[dict]: ...
